sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - env: STATIC_BUILD=ON COMPILER=g++
    - env: STATIC_BUILD=OFF COMPILER=g++

before_install:
# set CXX variable
  - export CXX=${COMPILER}
  - echo ${CXX}

# Make a 'deps' dir to hold installed stuff (boost)
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

install:
# Install build tools
# Need to add a PPA to get cmake 3.x
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get -y install gcc g++ cmake-data cmake

  - $CXX --version
  - cmake --version

# Cegui deps
  - sudo apt-get -y install libfreetype6-dev libsilly-dev libxml2-dev libexpat1-dev libgles2-mesa-dev libglfw-dev libglew-dev libglm-dev

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  # The -DGLM_FORCE_RADIANS is to silence a bunch of warnings, not necessary for build,
  # but too hard to install more recent GLM on debian.
  - cmake -DCEGUI_BUILD_RENDERER_OPENGL=ON -DCEGUI_BUILD_RENDERER_OPENGL3=ON -DCEGUI_BUILD_STATIC_CONFIGURATION=${STATIC_BUILD} -DCEGUI_BUILD_STATIC_FACTORY_MODULE=${STATIC_BUILD} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CXX_FLAGS=-DGLM_FORCE_RADIANS ../
  - make -j2
